import { StyledAnnounceCard } from "./style"
import photoCruze from '../../../../statics/cruze-sport6-rs-carros.webp'
import { CircleInitials } from "../../../../components/circle_initials";
import { useRequests } from "../../../../hooks/RequestsHooks";
import { useNavigate } from "react-router-dom";
// Generated by https://quicktype.io

export interface IAnnouncesReponse {
    id: number;
    km: number;
    price_fipe: number;
    price: number;
    description: string;
    image: string;
    withinFipe: boolean;
    createdAt: string;
    updatedAt: string;
    deletedAt: null;
    softDeleted: boolean;
    publishedAt: boolean;
    mark: string;
    model: string;
    fuel: string;
    color: string;
    owner: Owner;
    year: string;
}

export interface Owner {
    name: string;
    email: string;
    cpf: string;
    phone: string;
    birthDate: string;
    description: string;
    type: string;
    admin: boolean;
}
interface IAnnonuceProps {
    announce: IAnnouncesReponse,
    className: string
    onClick?: ()=> void
}


export const AnnounceCard = ({ announce, className, onClick }: IAnnonuceProps) => {
    const navigate = useNavigate()
    const handleNavitateToAnnounceDetail = () =>{
        navigate(`/announce-detail/${announce.id}`)
    }
    return (
        <StyledAnnounceCard className={className} onClick={handleNavitateToAnnounceDetail}>
            <div className="car-image-container">
                <img src={announce.image} alt="" />
            </div>
            <div className="announce-infos">
                <p className="model-name">{announce.model}</p>
                <p className="annunce-description">{announce.description}</p>
                <div className="owner-info">
                    <CircleInitials first={announce.owner.name[0]} size={2} color="#E34D8C"/>
                    <span>{announce.owner.name}</span>
                </div>
                <div className="car-infos">
                    <div className="left-side">
                        <span>{announce.km} KM</span>
                        <span>{announce.year}</span>
                    </div>
                    <div className="right-side">
                        <span>{announce.price.toLocaleString('pt-BR', {style: 'currency',currency: 'BRL'})}</span>
                    </div>
                </div>
            </div>
        </StyledAnnounceCard>
    )
}